version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"

    env_file:
      - .env
    volumes:
      - .:/app
      - app-data:/app/db

volumes:
  app-data:
